### ISSUE TITLE
ModuleNotFoundError: No module named 'symphony.bdk'

### ISSUE THREAD

**Issue by yottahmd** [finos/symphony-bdk-python#291]
I am facing the below error when I try to run the template project. How can I fix this?

Setup :
```sh
$ mkdir bdk-bot && cd bdk-bot
$ yo @finos/symphony

$ python3 -m venv env
$ pip3 install -r requirements.txt
$ pip3 install symphony
```

Error : 
```sh
$ source env/bin/activate
$ python3 -m src
Traceback (most recent call last):
  File "/Python-3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Python-3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 6, in <module>
    from symphony.bdk.core.activity.command import CommandContext
ModuleNotFoundError: No module named 'symphony.bdk'
```

**Comment by yottahmd** [comment]
Solved, thanks
